# Generated by Django 6.0.7 on 2026-07-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('apellidos_nombres', models.CharField(max_length=150, verbose_name='Apellidos y Nombres')),
                ('turno', models.CharField(choices=[('Día', 'Día'), ('Noche', 'Noche'), ('Reimpresión de credencial', 'Reimpresión de credencial')], max_length=50, verbose_name='Turno')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciales',
                'ordering': ['fecha_registro'],
            },
        ),
    ]
